### ISSUE TITLE
Swift 3.0 Syntax

### ISSUE THREAD

**Issue by jschwendt** [Driftt/drift-sdk-ios#10]
I'm getting error from the swift convertor saying that the Drift project is not Swift 3.0 compatible out of the box.  It looks like it's half upgraded.  Can you double check to ensure it's fully updated to avoid this issue?

**Comment by eoinoconnell** [comment]
Hi @jschwendt how are you installing the SDK? If you using cocoa pods you will need to use `pod 'Drift-SDK', :git => 'https://github.com/Driftt/drift-sdk-ios.git'` for now as we have yet to send it to the main cocoa pods repo

**Comment by jschwendt** [comment]
Yes, that's exactly what I'm doing.

**Comment by eoinoconnell** [comment]
Ok great, was working for me but ill take another look. Anything out of ordinary with your setup?

**Comment by jschwendt** [comment]
No...pretty straight forward.  Note that I'm integrating this into an Objective C project, so I had to add "use_frameworks!" to my Podfile.  You might need to fully clean your environment in order to reproduce.

**Comment by eoinoconnell** [comment]
Hi @jschwendt I think we found the issue, it looks like it was solved in cocoa pods V1.1.1 which was recently released, can you confirm your version for me?

**Comment by jschwendt** [comment]
Yes, I'm on 1.1.1 as well.  Sounds like we found the culprit 👍

**Comment by eoinoconnell** [comment]
hi @jschwendt ok great, was cocoa pods the issue?

**Comment by jschwendt** [comment]
So that didn't appear to fix it.  When I pull down this pod, I find that I have to fix about 20 things.  The fall under two different categories.  The first has to do with "_map" vs. "map".  The second has to do with extraneous "urlstring:" params.  I'm able to recover from this by manually fixing each item, but it happens each and every time I run a pod update since I'm always pulling from a specific repo, so it's incredibly annoying.

**Comment by eoinoconnell** [comment]
Hi @jschwendt That seems odd, we're testing it here without any issues, can you give me an example of where exactly its asking you to update the code?

**Comment by jschwendt** [comment]
Here's a step by step set of screenshots of what I encounter every time I run pod update with my project.  When I remove the Drift Pod, this all goes away.  Note that I'm using an Objective C project with many other pods included.  To make matters worse, when I go to build for a device, all of the frameworks have to be signed each time, so my build times have gone from 10 seconds to 4 minutes due to this.

<img width="1440" alt="screen shot 2016-12-12 at 1 29 48 pm" src="https://cloud.githubusercontent.com/assets/408757/21111539/1c1d383e-c070-11e6-89e6-e07673f17fc5.png">
<img width="1440" alt="screen shot 2016-12-12 at 1 30 17 pm" src="https://cloud.githubusercontent.com/assets/408757/21111538/1c1ca2f2-c070-11e6-9764-002bd9809602.png">
<img width="1440" alt="screen shot 2016-12-12 at 1 30 27 pm" src="https://cloud.githubusercontent.com/assets/408757/21111542/1c1d9fd6-c070-11e6-885a-1eeddc108764.png">
<img width="1440" alt="screen shot 2016-12-12 at 1 30 40 pm" src="https://cloud.githubusercontent.com/assets/408757/21111537/1c1c6904-c070-11e6-8835-b9db9655b223.png">
<img width="1440" alt="screen shot 2016-12-12 at 1 35 16 pm" src="https://cloud.githubusercontent.com/assets/408757/21111540/1c1d2fb0-c070-11e6-93f1-d265cf4a2122.png">
<img width="1440" alt="screen shot 2016-12-12 at 1 35 26 pm" src="https://cloud.githubusercontent.com/assets/408757/21111541/1c1d94fa-c070-11e6-9eb4-683d88a236c8.png">
<img width="1440" alt="screen shot 2016-12-12 at 1 35 29 pm" src="https://cloud.githubusercontent.com/assets/408757/21111543/1c24bbcc-c070-11e6-8ce8-c86564e27115.png">
<img width="1440" alt="screen shot 2016-12-12 at 1 35 35 pm" src="https://cloud.githubusercontent.com/assets/408757/21111546/1c2624bc-c070-11e6-97bb-bcc1eb56b0ee.png">
<img width="1440" alt="screen shot 2016-12-12 at 1 35 39 pm" src="https://cloud.githubusercontent.com/assets/408757/21111544/1c25a730-c070-11e6-8877-ba63acc73d9e.png">
<img width="1440" alt="screen shot 2016-12-12 at 1 35 42 pm" src="https://cloud.githubusercontent.com/assets/408757/21111547/1c26976c-c070-11e6-8de1-3effe511bb72.png">
<img width="1440" alt="screen shot 2016-12-12 at 1 35 47 pm" src="https://cloud.githubusercontent.com/assets/408757/21111545/1c26007c-c070-11e6-8cc0-91dee4676104.png">
<img width="1440" alt="screen shot 2016-12-12 at 1 35 50 pm" src="https://cloud.githubusercontent.com/assets/408757/21111548/1c2733f2-c070-11e6-83a7-6b004e051fee.png">
<img width="1440" alt="screen shot 2016-12-12 at 1 35 52 pm" src="https://cloud.githubusercontent.com/assets/408757/21111549/1c2d5b2e-c070-11e6-8b0f-4ccc44569292.png">
<img width="1440" alt="screen shot 2016-12-12 at 1 35 58 pm" src="https://cloud.githubusercontent.com/assets/408757/21111550/1c2e1e1a-c070-11e6-87fa-0f7c6798e9ec.png">
<img width="1440" alt="screen shot 2016-12-12 at 1 36 06 pm" src="https://cloud.githubusercontent.com/assets/408757/21111551/1c2e7d92-c070-11e6-9b03-70b1310e3ef2.png">
<img width="1440" alt="screen shot 2016-12-12 at 1 36 10 pm" src="https://cloud.githubusercontent.com/assets/408757/21111553/1c3087ae-c070-11e6-838c-b254e6f87881.png">
<img width="1440" alt="screen shot 2016-12-12 at 1 36 18 pm" src="https://cloud.githubusercontent.com/assets/408757/21111552/1c2ee318-c070-11e6-9e53-73a1adfe31e8.png">
<img width="1440" alt="screen shot 2016-12-12 at 1 36 21 pm" src="https://cloud.githubusercontent.com/assets/408757/21111554/1c30b7ec-c070-11e6-8532-a471e8e88724.png">
<img width="1440" alt="screen shot 2016-12-12 at 1 36 23 pm" src="https://cloud.githubusercontent.com/assets/408757/21111555/1c363604-c070-11e6-8832-e94168568779.png">
<img width="1440" alt="screen shot 2016-12-12 at 1 36 26 pm" src="https://cloud.githubusercontent.com/assets/408757/21111557/1c37c550-c070-11e6-8df1-4010f20dccf9.png">
<img width="1440" alt="screen shot 2016-12-12 at 1 36 32 pm" src="https://cloud.githubusercontent.com/assets/408757/21111556/1c370dd6-c070-11e6-96f5-30848ecacd50.png">
<img width="1440" alt="screen shot 2016-12-12 at 1 36 36 pm" src="https://cloud.githubusercontent.com/assets/408757/21111558/1c3a5ed2-c070-11e6-9f3c-8d507e2a9a9c.png">
